server: 
  port: 8081
spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: postgres
    password: 06082001arthur
  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    #UTILISER LA COMMANDE CI DESSOUS POUR CREER LA BASE DE DONNEES ET APRES METTRE EN COMMENTAIRE
    #hibernate.ddl-auto: create
